RISK_PHRASES = {
    "en": {
        "urgent": ["chest pain", "fell", "ambulance", "can't get up", "severe pain"],
        "poor_sleep": ["did not sleep", "poor sleep", "couldn't sleep", "bad sleep"],
        "food": ["didn't eat", "no appetite", "not hungry", "ate nothing"],
        "water": ["didn't drink", "no water", "dehydrated"],
        "fatigue": ["tired", "very tired", "weak", "exhausted"],
        "dizziness": ["dizzy", "lightheaded"],
        "emotional": ["lonely", "sad", "anxious", "depressed"],
        "medication": ["missed medicine", "forgot medicine", "didn't take medicine"],
    },
    "fi": {
        "urgent": ["rintakipu", "kaaduin", "ambulanssi", "en pääse ylös", "kova kipu"],
        "poor_sleep": ["nukuin huonosti", "en saanut unta", "huono uni"],
        "food": ["en syönyt", "ruoka ei maistu", "ei ruokahalua"],
        "water": ["en juonut", "liian vähän vettä", "kuivunut"],
        "fatigue": ["väsynyt", "heikko", "uupunut"],
        "dizziness": ["huimaa", "pyörryttää"],
        "emotional": ["yksinäinen", "surullinen", "ahdistunut"],
        "medication": ["unohdin lääkkeet", "en ottanut lääkettä"],
    },
    "sv": {
        "urgent": ["bröstsmärta", "jag föll", "ambulans", "kan inte resa mig", "svår smärta"],
        "poor_sleep": ["sov dåligt", "kunde inte sova", "dålig sömn"],
        "food": ["åt inte", "ingen aptit", "åt ingenting"],
        "water": ["drack inte", "för lite vatten", "uttorkad"],
        "fatigue": ["trött", "svag", "utmattad"],
        "dizziness": ["yr", "yrsel"],
        "emotional": ["ensam", "ledsen", "orolig"],
        "medication": ["glömde medicin", "tog inte medicin"],
    },
}