version: "3.9"

services:
  db:
    image: postgres:16
    container_name: welfare_bot_db
    environment:
      POSTGRES_DB: welfare_bot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: